### ISSUE TITLE
chila_pcb.intlib

### ISSUE THREAD

**Issue by JamilAhmadiRovari** [aKaReZa75/RCS_AVR#1]
سلام و عرض ادب خدمت شما دوست گرامی
تسلیت ما رو بخاطر  وفات دوست گرامیتان پذیرا باشید و برای شما و خانواده آن مرحوم صبر جمیل را از خداوند متعال خواستاریم
دوست گرامی 
متاسفانه در GitHub  کتابخانه مربوطه رو بصورت intlib و یکپارچه  پیدا نکردم و به شخصه دارم بصورت pcb و شماتیک استفاده میکنم که مزایای خودش رو داره اگه لینک مربوطه رو برای دانلود بزارید ممنون میشم

**Comment by aKaReZa75** [comment]
سلام و عرض ادب، ممنونم از محبت و بزرگی و مهربانی شما.
فایلی که عرض کردم توی ویدئوی بعدی اضافه میکنم، اما اگه نیاز به اون قطعات دارید کتابخانه کامل رو میتونید از طریق لینک زیر دانلود کنید:
https://www.mediafire.com/file/jqd9kgzzjb5zkfy/Chila_PCB.IntLib/file

**Comment by omid402** [comment]
با سلام عرض تسلیت خدمت شما دوست گرامی
خواستم چند نکته درباره طراحی قسمت تغذیه با توجه به تجربه خودم در مورد کار با GSM ها بگم
ماژول های gsm بسیار نسبت به تغذیه حساس هستند و رگولاتور سویچینگ برای آنها مناسب نیستند بهترین انتخاب رگولاتر خطی MIC29302 هست
با توجه به بلوک های که در طرح مفهومی ارائه کردین شما نیازی به ولتاژ 3.3 ولت و 5 ولت ندارید LCD کاراکتری ماژول گیرنده ریموت و آسی AVR با ولتاژ 4 ولت کار میکنه
