### ISSUE TITLE
AVR Pins

### ISSUE THREAD

**Issue by HamidRezaKarimiS** [aKaReZa75/RCS_AVR#11]
سلام
با توجه به محدود بودن Pin های میکرو، پیشنهاد میکنم پایه هایی که لازم داریم رو ابتدا مشخص کنیم تا در ادامه کمتر مشکل ایجاد بشه.
من پایه های کریستال خارجی رو در صفحه controller تخصیص دادم و pull کردم.

اگر صلاح میدونید، نوع ارتباط LCD، GSM و حتی ماژول ریموت هم مشخص کنید.

**Comment by HamidRezaKarimiS** [comment]
سلام
برای جذاب تر شدن پروژه پیشنهاد میکنم.
پایه ماژول ریموت به int0 متصل بشه
نمایشگر با i2C متصل بشه و ماژول GSM( اگر از 800L استفاده میشه) با uart نرم افزاری به میکرو متصل بشه و uart اصلی با usbtottl به یه کامپیوتر برای debug متصل بشه.

**Comment by aKaReZa75** [comment]
سلام و عرض ادب خدم شما دوست عزیز، بله موافقم با شما، ولی به احتمال زیاد از کریستال خارجی استفاده نکنیم، به نظرم پایه های IO کافی هستند تا ال سی دی رو به صورت موازی راه اندازی کنیم.
چونکه خد ال سی دی رو داریم از همون میشه به عنوان دیباگ استفاده کرد و درده سر UART نرم افزاری رو نداشته باشیم.
در خصوص اینکه گفتین Pull فرستادین، احتمالا اشتباهی شده، یکبار دیگه مرور کنید چونکه ریکوئست سمت من نیامده.
ممنونم از اینکه نظر خودتون رو بیان کردید.

**Comment by HamidRezaKarimiS** [comment]
> در خصوص اینکه گفتین Pull فرستادین، احتمالا اشتباهی شده، یکبار دیگه مرور کنید چونکه ریکوئست سمت من نیامده. ممنونم از اینکه نظر خودتون رو بیان کردید.

آره ظاهرا بلد نیستم، هر کاری کردم که نشد. ادامه میدم تا بشه.
