### ISSUE TITLE
TPS54302 SIMULATION IN ORCAD CADENCE

### ISSUE THREAD

**Issue by JamilAhmadiRovari** [aKaReZa75/RCS_AVR#13]
سلام و عرض ادب خدمت استاد گرامی
![AkaReza_calculating](https://github.com/user-attachments/assets/c6356b39-1a46-4fa7-b741-d5a91709d142)
محاسبه قطعات و شبیه سازی مدار طبق ویدئو 
**#**aKaReZa 72 - RCS, AVR  - PART C.mp4**** 
![My_calculating-120pF-13 7k](https://github.com/user-attachments/assets/f5742212-576b-46bb-b8fc-4d2a17ba68ff)
محاسبه قطعات و شبیه سازی مدار با خازن فیدبک 120pF و مقاومت 13.7 کیلو  مطابق با توضیحات ویدئو
**# **aKaReZa 65 - PCB, Switching Regulato.mp4****
![My_calculating-120pF-13 6k](https://github.com/user-attachments/assets/f620f064-3a07-41b2-8118-9502b5177376)
محاسبه قطعات و شبیه سازی مدار با خازن فیدبک 120pF و مقاومت 13.6 کیلو  مطابق با توضیحات ویدئو
 ****aKaReZa 65 - PCB, Switching Regulato.mp4**** 

**************      **در انتظار ویدئوی بعدی**      ************************

**Comment by aKaReZa75** [comment]
سلام و عرض ادب خدمت شما، بسیار ممنونم از محبت شما، بسیار کار با ارزشی رو انجام دادید، توی ویدئو بعدی بررسی میشه.

**Comment by JamilAhmadiRovari** [comment]
سلام استاد گرامی
این ادرس ایمیل برای دسکتاپ اینجانب میباشد و متاسفانه سینک نیست و خیلی دیر
متوجه میشم
بابت دیر متوجه شدن پیام های شما عذر بنده را پذیرا باشید
متشکرم

**Comment by aKaReZa75** [comment]
خواهش میکنم دوست عزیز، مسئله ای نداره، موفق باشید.
