### ISSUE TITLE
Power design

### ISSUE THREAD

**Issue by omid402** [aKaReZa75/RCS_AVR#2]
با سلام و عرض تسلیت خدمت شما دوست گرامی
خواستم چند نکته درباره طراحی قسمت تغذیه با توجه به تجربه خودم در مورد کار با GSM ها بگم
1-ماژول های gsm بسیار نسبت به تغذیه حساس هستند و رگولاتور سویچینگ برای آنها مناسب نیست بهترین انتخاب رگولاتر خطی MIC29302 هست
2-با توجه به بلوک های که در طرح مفهومی ارائه کردین شما نیازی به ولتاژ 3.3 ولت و 5 ولت ندارید LCD کاراکتری , ماژول گیرنده  ریموت و آسی AVR با ولتاژ 4 ولت کار میکنه

**Comment by tajmirik** [comment]
از لحاظ تامین جریان به مشکل نمیخوریم اگر برای همه از mic29302 استفاده کنیم ؟
مگر این که دو یا سه تا از همین رگولاتور بذاریم

**Comment by tajmirik** [comment]
<img width="625" alt="TPS54302_adj_out_in8-12v" src="https://github.com/user-attachments/assets/7c1b325b-7ff9-456f-af33-2f42cfd8f680">

**Comment by omid402** [comment]
این رگولاتور MIC29302 تا 3 آمپر جریان دهی داره و پیشنهاد شده در کاتالوگ GSM   هم هست من از این رگولاتور استفاده کردم و از خروجی 4.1 ولت برای SIM800C  ATMAGA64, LCD2*16, LM386 و ماژول گیرنده FSK استفاده کردم  کاملا OK بود و تعداد زیادی از این برد تولید کردم هیچ مشکلی نداشته

**Comment by aKaReZa75** [comment]
> با سلام و عرض تسلیت خدمت شما دوست گرامی 
>
سلام و عرض ادب، بسیار ممنونم از لطف شما، انشالله همیشه سلامت باشید.

> خواستم چند نکته درباره طراحی قسمت تغذیه با توجه به تجربه خودم در مورد کار با GSM ها 
> 
ممنونم از لطف شما

> 1-ماژول های gsm بسیار نسبت به تغذیه حساس هستند و رگولاتور سویچینگ برای آنها مناسب نیست بهترین انتخاب رگولاتر خطی MIC29302 هست
> 
بله کاملا همینطوره، اما بستگی داره از چه رگولاتوری با چه فرکانس و همینطور از چه فیلتری برای اون استفاده کرده باشید، اما کاملا موافقم با شما که رگولاتور های خطی خیلی خیلی در خصوص مباحث نویز و ... کم درده سر تر هستند و پیشنهاد خوبی هست که از رگولاتور خطی استفاده کنیم.

> 2-با توجه به بلوک های که در طرح مفهومی ارائه کردین شما نیازی به ولتاژ 3.3 ولت و 5 ولت ندارید LCD کاراکتری , ماژول گیرنده ریموت و آسی AVR با ولتاژ 4 ولت کار میکنه
> 
بله کاملا درست میفرمایید و میشه رگولاتورهایی که فرمودید رو حذف کرد، اما باید با دید اینکه این پروژه اموزشی هست نگاه کرد و هدف یادگرفتن بیشتر هست و ملاحظاتی که برای یک محصول تجاری هست بسیار متفاوت هست بایک پروژه آموزشی.
مورد دوم هم این هست که این برد قراره برای سایر میکروکنترلرهای دیگه غیر از AVR هم استفاده بشه و درسته که شروعش با AVR هست که میتونه رنج تغذیه 3.3 تا 5 ولت رو داشته باشه، اما میکروکنترلرهای دیگه ای که با اونها کار میکنیم اینطوری نیستند و همگی 3.3 ولت هستند، اگه از اول این بخش رو طراحی کنیم، برای بقیه میکروکنترلرها کار ما ساده تر میشه و نیازی به تغییر بلوک تغذیه نیست.

 ممنونم از توجهتون و نکاتی که فرمودید.
