### ISSUE TITLE
من با این محیط کنار نمیام استاد ،خواستم جواب سوال ویدیوی آخر رو بدم

### ISSUE THREAD

**Issue by omid-mazarei** [aKaReZa75/RCS_AVR#20]
سلام استاد
 ویدیوی آخر هم واقعا عالی بود ولی من با این محیط هنوز نتونستم کنار بیام به هر حال اینجا جواب سوالی که مطرح کردین رو میزارم

به هر حال معذرت میخوام
البته میدونم مقدار ها دقیق نیست
ادیت:البته این مدار یه ایرادی هم داره اونم باز گذاری  اپتو کوپلر روی تقسیم مقاومتی است که فکر کنم یک آپ امپ یا کامپراتور نیاز باشه
![220](https://github.com/user-attachments/assets/30aee967-74e1-4261-ae24-f9f2ad515b7b)

ادیت شماره 2
فکر میکنم این بهتر باشه

![220_1](https://github.com/user-attachments/assets/148f88a5-8140-4c1b-858e-84d4c5dfc7f1)

البته اگه دقت و سرعت بیشتری بخواهیم یک LM311 را بجای فیلتر بعد از اپتو کوپلر و قبل از میکرو بذاریم چون احتمالا ابن خازنها تاخیر ایجاد می کنند

البته اشمیت تریگر هم احتمالا میشه گذاشت

**Comment by aKaReZa75** [comment]
سلام و عرض ادب، ممنونم از شما، توی ویدئو مربوطه بررسی خواهد شد، موفق باشید.

**Comment by omid-mazarei** [comment]
سلام  و عرض ادب استاد،ممنون از راهنمایی هاتون،ابتدا تشکر می کنم ازاینکه قابل دونستین  تحلیلی که روی این شماتیک انجام دادین ،فرمودین که احتمالا این بخش دیتکتور از پروژه حذف میشه ولی برای جنبه آموزشی خودم اینو میخواستم خدمتتون عرض کنم که اون دیود زنر رو بیشتر از اینکه برای محافظت از اپتو کوپلر بذارم برای این گذاشته بودم که خارن صافی کوچک بشه،استدلال  من هم این بود که با توجه به امپدانسی (مقاومت فرکانسی ،اگر اسم درستش باشه) که خازن سری ایجاد میکنه کلا جریان کوچکی خازن سری و قسمت دیتکتور اپتو کوپلر رد خواهد شد پس زنر هم می تونه این جریان کم رو تحمل کنه ومی تونه ولتاژ رو در حد همون 5 ولت نگه دارده پس ولتاژ دو سر خازن صافی c1 از ولتاژ زنر که 5 ولته بیشتر نخواهد شد پس یرای خازن صافی احتیاج به خازن ولتاژ بالا نخواهد بود و با یک خازن الکترولیتی 15 ولت مسئله حله،اینکه از یکسو ساز نیم موج هم استفاده کردم هم برا کم شدن" حجم مدار "بود و هم "خودش به کم شدن توان کمک میکنه" وگرنه از تمام موج استفاده می کردم، در باره مقاومت 330 اهم هم که فرمودین حتما کافیه چون همانطور که مشاهده میکنین کلا 10 میلی امپر برای روشن شدن ال ای دی اپتو کوپلر عبور میکنه که مطابق دیتا شیته،من اینو در پرتئوس شبیه سازی کردم و عمدا ولتاژ و جریان قسمت های مهم  رو هم با ولت متر و امپر متر پرتئوس اندازه گیری کردم که در  شماتیک است و اگر درست باشه خوب برای کار عملی احتیاج به این ولت متر و امپر مترها نیست البته در باره بقیه موارد از جمله مقدار مقاومت موازی با خازن و گذاشتن مقاومت 10 اهمی در نول و اون فسمت فیلتر بعد از اپتو کوپلر اطلاعات خوبی بمن داداه شد و از این بابت متشکرم،اون مدار دوستمون هم خوب بود ولی چند ایراد من دارم 1-برای یک همچین موردی که جریان زیادی نمی خواییم بنظر من همون یک عدد دیود و یکسو سازی نیم موج کافیه که برای یک دیتکتور که باید کوچک باشد بهتره،واون مقاومت 1 کیلو اهم هم که قبل از اپتو کوپلر گذاشتن با توجه به ولتاژ دو سر مقاومت و جریان عبوری باید اقلا 2 وات باشد که بزرگ است ،اینو هم تو شبیه ساز تست کردم حدودا .7 وات مصرف مقاومت قبل از اپتو کوپلره. لطفا جهت جنبه اموزشی ارشاد بفرمایید ممنون

**Comment by aKaReZa75** [comment]
سلام . عرض ادب مجدد خدمت شما.
اول از هر چیزی میخوام یک اعتراف کنم و اونم این هست که من اصلا متوجه نشدم که اون دیود، دیود زنر هست! خیلی وقته با پروتئوس کار نمیکنم و نماد زنر توی پروتئوس  غیر متعارف هست، برای همین اصلا متوجه نشدم، اما قرار دادن زنر کار درستی هست و باعث میشه اون مشکل اضافه ولتاژی که بنده عرض کردم وجود نداشته باشه و حداقل اپتوکوپلر بخاطر ولتاژ بالا نسوزه!
در خصوص نیم موج بودن یا تمام موج بودن بنده کماکان نظرم بروی تمام موج هست، ولی این مدار شمارو هم تست میکنیم ( به صورت عملی)
در خصوص مقاومت 330 اهم، با توجه به اینکه من اصلا متوجه زنر نشده بودم، با وجود زنر، مقدار این مقاومت توجیح پذیر هست و حق با شماست.
در خصوص ولتاژ خازن صافی هم حق با شماست، با وجود زنر مقدار ولتاژ خازن خیلی کم میشه و حجمش کوچیک میشه به طبع.
دو نکته هم در خصوص شبیه سازیتون عرض کنم، اول اینکه زمین دو سمت اپتوکوپلر نباید یکی باشه، چونکه هدف ایزولاسیون هست، پس باید زمین ها حتما متفاوت باشند.
مورد دوم هم توی این نوع مدار های خیلی مهمه حالت گذرا هم تحلیل بشه که مدار توی زمانی که برای بار اول قراره متصل بشه، رفتارش و جریان اولیه به چه شکل هست که توی آموزش پارت دوم پروتئوس این موضوع رو دیدیم.
حالا چه این قسمت از مدار حذف بشه و چه نشه! در هر دو صورت خودموت به صورت عملی یک مدار مناسب برای این موضوع طراحی میکنیم چونکه خیلی کاربردی هست و قطعا از مدار پیشنهادی شما و ددوست عزیزه دیگمون کمک میگیرم و به یک مدار نهایی میرسیم.
بازم از شما هم ممنونم و هم عذر میخوام، موفق باشید.
