### ISSUE TITLE
تغییر نحوه نصب و قرار گیری دستگاه

### ISSUE THREAD

**Issue by aKaReZa75** [aKaReZa75/RCS_AVR#21]
سلام و عرض ادب، لطفا نظر خودتون رو در خصوص تغییر و نحوه نصب جعبه رو بفرمایید و حتی اگر پیشنهاد بهتری رو دارید همینجا بفرمایید:

![43898-9330617092203](https://github.com/user-attachments/assets/bd78ebd8-2092-4c0d-abd9-ff6e96e01b9b)

توی این روش دیگه خود کلید کولر رو باز میکنیم و دستگاه رو بجای کلید کولر قبلی نصب میکنیم.

![20110713190753248-500x500](https://github.com/user-attachments/assets/f26a972f-e8e2-4b9f-a97b-b6b2f3f42ebd)

چونکه خود جعبه Wall-Mount هست خیلی راحت میشه جعبه رو به دیوار متصل کرد.

**Comment by hisec1** [comment]
سلام استاد به نظرم اینجوری کار شکیل و بهتر در می یاد با پیشنهاد شما موافقم
