### ISSUE TITLE
نصب کنار کلید

### ISSUE THREAD

**Issue by mm-mohammadi** [aKaReZa75/RCS_AVR#23]
این نوع طراحی بسیار منطقی و بهینه بنظر میرسه

**Comment by aKaReZa75** [comment]
سلام و عرض ادب، ممنونم از بیان نظرتون.
ایشیو مربوط به این موضوع در لینک زیر هست:
https://github.com/aKaReZa75/RCS_AVR/issues/21
موفق باشید.
