### ISSUE TITLE
تغییر ای سی 

### ISSUE THREAD

**Issue by mm-mohammadi** [aKaReZa75/RCS_AVR#24]
سلام و عرض ادب ، ضمن تشکر از شما  اگر امکان داره از ای سی دیپ  استفاده کنید چرا که اکثر ما چند تایی از ان رو داریم و در ظمن تعویض این قطعه به هر دلیل به مراتب اسان تر و دردسترس تر خواهد بود.

**Comment by aKaReZa75** [comment]
سلام و عرض ادب، بله چشم توی ویدئو بعدی این موضوع مطرح میشه، اگر کسی انجام دادم که چه عالی اونو کناب پروژه اصلی قرار میدم اگرم که نه خودم یه نسخه DIP رو هم میسازم و قرار میدم، اما بیس اصلی این پروژه و همه پروژه های بعدی SMD هست. موفق باشید
