### ISSUE TITLE
ساخت کتابخانه یکپارچه از سایر کتابخانه ها

### ISSUE THREAD

**Issue by mm-mohammadi** [aKaReZa75/RCS_AVR#25]
با عرض سلام و تشکر صمیمانه از آموزش های بسیار خوبتون لطفا یک ویدیو برای ساخت کتابخانه یکپارچه از سایر کتابخانه ها بطور مثال اضافه کردن یک قطعه از chilapcb به کتابخانه شخصی خودمان

**Comment by aKaReZa75** [comment]
سلام و عرض ادب خدمت شما، بله ویدئو مربوط به ساخت کتابخانه التیوم رو پارت اولشو ساختم، و ادامه دار هم هست، این موضوعی که فرمودید روهم در نظر دارم که ریکورد کنم توی پارتهای بعدی، موفق باشید.
