### ISSUE TITLE
Power Supply

### ISSUE THREAD

**Issue by mehrdadqasemitaj** [aKaReZa75/RCS_AVR#3]
سلام جناب مهندس. تسلیت میگم روحشون شاد و نامشون جاودان . چندتا پیشنهاد داشتم برای طراحی 1-وجود چند پوش باتن و یا کی پد برای تنظیم کردن سنسور های دما و رطوبت و وجود بازر برای هشدار علاوه بر اس ام اس . 2- اس ام اس و آلارم در صورت قطعی برق .3- در نمونه پیشرفته تر میتونه گرفتن فیدبک هایی از وضعیت کولر باشه مثلا موتور و یا پمپ به درستی کار میکنند یا خیر .
برای قسمت تغذیه دوازده ولت آیا میشه به جای استفاده از آداپتور قاب دار از منبع تغذیه که به صورت pcb هست(بدون قاب ) استفاده کنیم و داخل باکس کنار مین برد ببندیم که البته میتونه باعث نویز بشه رو برد اصلی اما با راه کار هایی مثل شیلد کردن منبع این اثر رو کم کنیم . 
برای قسمت tps54302 اول پیشنهاد ام رو میگم و بعد محاسبات .طبق تجربه دوستان و نه خودم استفاده از خازن تانتالیوم 6.3 و حتی 10 ولت در مدارات با ولتاژ 5 ولت باعث سوختن خازن ها شده بود و همچین برد توسعه ایی که خود تگزاس گذاشته داخل سایتش از خازن های مولتی لایر استفاده کرده.
محاسبات برای خروجی پنج ولت : 
R2 = 100 k
R1 = 13.7 K
L = 8.1 UH = 10 uH / 3.5A
COUT = 56 uF / 10V 
Cff = 87 pF = 100 pF
_ البته داخل دیتاشیت برای خروجی پنج ولت دو عدد خازن 22 میکرو فاراد پیشنهاد داده . 
_ برای خرید مقاومت 13.7 کیلو هم فروشگاه "کاالکترونیک" در سایز 805 و 1206 موجوده . لینکش رو میزارم 
https://kaelectronic.ir/index.php?route=product/product&product_id=6845
![tps54302boardtxins (1)](https://github.com/user-attachments/assets/af98add3-df15-4cbb-a771-96f4d34d011f)
![tps54302boardtxins (2)](https://github.com/user-attachments/assets/e9f60f1c-99d7-48ba-b5be-4677277fa6e2)

**Comment by aKaReZa75** [comment]
> سلام جناب مهندس. تسلیت میگم روحشون شاد و نامشون جاودان
> 
سلام و عرض ادب، بسیار ممنونم از لطف شما، انشالله همیشه سلامت و پایدار باشید.

> چندتا پیشنهاد داشتم برای طراحی
> 
ممنونم از پیشنهاد هاتون، باهم همرو بررسی میکنیم:

> 1-وجود چند پوش باتن و یا کی پد برای تنظیم کردن سنسور های دما و رطوبت و وجود بازر برای هشدار علاوه بر اس ام اس
> 
در خصوص قرار دادن پوشباتن مسئله ای ازین بابت نیست ( که پوش باتن رو اضافه کنیم)، شاید بهترش این باشه با خود اس ام اس دادن تعیین کنیم این حدود رو، به نظرتون این کار بهتر نیست؟ تا اینکه بریم پای دستگاه و روی پیشتبام و...
کلید رو قرار میدیم اما پیشنهاد خودم استفاده از کلید برای تعریف و تغییر ریموت ها هست.
در خصوص بازر هم میشه اضافه کرد اما مسئله اینجاست که دستگاه کنار کولر نصب میشه و ما دسترسی راحتی به اون نداریم، آیا باز به نظرتون میتونه کارآمد باشه؟

> 2- اس ام اس و آلارم در صورت قطعی برق 
> 
بسیار پیشنها خوب و کاربردی هست اما مسئله ای که داره این هست که باید برای اون باتری نصب کنیم تا بتونه اس ام اس رو بفرسته، و اضافه کردن باتری یعنی باید مدار شارژ اون رو هم اضافه کنیم، اما خوب خیلی هم کار سختی نیست، میتونیم نظر بقیه دوستان رو هم بپرسیم.

> 3- در نمونه پیشرفته تر میتونه گرفتن فیدبک هایی از وضعیت کولر باشه مثلا موتور و یا پمپ به درستی کار میکنند یا خیر .
> 
این کارو هم میشه با اضافه کردن سنسور جریان و وارد کردن مشخصات کولر ( حدود جریان کاری پمپ، دور کند و دور تند ) انجام دادم اما حجم مدار زیاد میشه ولی خب شدنی هست.

> برای قسمت تغذیه دوازده ولت آیا میشه به جای استفاده از آداپتور قاب دار از منبع تغذیه که به صورت pcb هست(بدون قاب ) استفاده کنیم و داخل باکس کنار مین برد ببندیم که البته میتونه باعث نویز بشه رو برد اصلی اما با راه کار هایی مثل شیلد کردن منبع این اثر رو کم کنیم .
> 
بله حتما میشه این کارو کرد ولی راه کم درده سرتر رو انتخاب کردم، ولی خیلی دستگاه جمع و جور تر میشه اگه آداپتور خارجی حذف بشه و تغذیه داخل خود دستگاه قرار بگیره.این مورد رو شاید بشه آخر کار پیاده کرد، ببینیم فضای کافی داریم داخل جعبه یا خیر.

> برای قسمت tps54302 اول پیشنهاد ام رو میگم و بعد محاسبات .طبق تجربه دوستان و نه خودم استفاده از خازن تانتالیوم 6.3 و حتی 10 ولت در مدارات با ولتاژ 5 ولت باعث سوختن خازن ها شده بود و همچین برد توسعه ایی که خود تگزاس گذاشته داخل سایتش از خازن های مولتی لایر استفاده کرده.
> 
خازن های تانتال به صورت کلی خیلی به ولتاژ حساس هستند و نباید اضافه ولتاژ داشته باشند، این شرایطی که میفرمایید حتما خود 5 ولت صاف نبوده و ریپل و اسپایک های زیادی داشته وگرنه خازن 10 ولت برای ولتاژ 5 ولت آسیب نباید ببینه، من خودم همیشه از 6.3 استفاده کردم برای 5 ولت و اوکی بوده.
مزیت اصلی تانتال ها نسبت به مولتی لایرها ESR پایین اونها هست و انتخاب بهتری هست اما هزینه کار رو بالا میبره، عموما توی کاربرد های تجاری این موضوع خیلی مهمه، ولی برای برد ما هزینه نهایی پروژه خیلی مهم نیست، چون یک محصول تجاری نیست و هدفش آموزش هست پس قیمت اگه بیشتر هم بشه مسئله ای نداره.

> محاسبات برای خروجی پنج ولت :
R2 = 100 k
R1 = 13.7 K
L = 8.1 UH = 10 uH / 3.5A
COUT = 56 uF / 10V
Cff = 87 pF = 100 pF
_ البته داخل دیتاشیت برای خروجی پنج ولت دو عدد خازن 22 میکرو فاراد پیشنهاد داده .
> 
ممنونم از محاسبه ای که زحمت کشیدین و انجام دادین ولی من هنوز محاسبه نکردم، هرموقع انجام دادم مقایسه میکنیم محاسبتمون رو باهم.

>  برای خرید مقاومت 13.7 کیلو هم فروشگاه "کاالکترونیک" در سایز 805 و 1206 موجوده . لینکش رو میزارم
https://kaelectronic.ir/index.php?route=product/product&product_id=6845
> 
ممنونم از لطف شما، صفحه خرید قطعات رو ویرایش میکنم و لینک شمارو اضافه میکنم.

از لطف شما ممنونم حسابی زحمت افتادید.

**Comment by mehrdadqasemitaj** [comment]
تمام نکاتی که گفتید منطقی بود و من یک جاهایی از پروژه رو اشتباه متوجه شده بودم و فک میکردم قراره دستگاه داخل خونه نصب شه نه روی پشتبام . مرسی از راهنمایی و نکات خوبتون
