### ISSUE TITLE
LED Resistor

### ISSUE THREAD

**Issue by mehrdadqasemitaj** [aKaReZa75/RCS_AVR#4]
مقادیر مقاومت برای ال ای دی ها : 
LED Green (3V3) : 90 ohm => 100 ohm 
LED Blue (4V) : 100 ohm
LED Red (5V) : 260 ohm => 330 ohm
LED Yellow (12V) : 960 ohm=>  1Kohm
_اعداد اول اعداد محاسبه شده و اعداد جلوی آنها استاندارد موجود مقاومت هاست .
مدار عملی هم برای تست شدت نور اونها بستم اما ال ای دی 0805 آبی نداشتم به جای آن 0603 گذاشتم که فک میکنم با اینکه سایز کوچک تری نسبت به سایر ال ای دی ها داره اما پرتاب نور بیشتری داره و شایدم بخاطر ماهیت نور ال ای دی آبی است .
![20240719_142742](https://github.com/user-attachments/assets/9bb41619-c2bd-4dd6-a0a6-c872b8e99ee8)
![1000060998](https://github.com/user-attachments/assets/d0cd8632-5a65-40cc-aa90-b0be4b58b433)
![1000060999](https://github.com/user-attachments/assets/ea80ab50-b5b2-4cc1-9d49-417703fded25)
![1000061000](https://github.com/user-attachments/assets/dc90016b-d030-48e6-b60d-f82309fb0221)

**Comment by aKaReZa75** [comment]
سلام و عرض ادب، بسیار ممنونم از زحمتی که کشیدید، بنده هنوز محاسبه نکردم ولی قطعا همرو درست حساب کردید.
بسیارهم لذت بردم از کارتون، خیلی عالی هست که همه چیو عملی تست میکنید.
موفق باشید.
