### ISSUE TITLE
تامین ولتاژ موزد نیاز ماژول GSM توسط دیود 1N4007

### ISSUE THREAD

**Issue by hamidtb** [aKaReZa75/RCS_AVR#7]
سلام، روزتون بخیر
نظرتون در باره تامین ولتاژ مورد نیاز ماژول GSM  توسط یک عدد دیود 1N4007 چی هست؟
به این صورت که ولتاژ 5 ولت توسط رگولاتور تامین بشه و توسط دراپ اوت دیود 1N4007 (حدود 0.7V) ولتاژ تقریبی 4.3 ولت برای ماژول ساخته بشه؟

**Comment by aKaReZa75** [comment]
سلام و عرض ادب.
خیر، به هیچ عنوان این موضوع پیشنهاد نمیشه، علتشم اینهکه ماژول های GSM بسیار حساس به تغذیه هستند و باید تغذیه اونها رگوله بشه و یک ولتاژ صاف، بدون نویز و ریپل به این ماژولها داده بشه تا عملکرد پایداری رو داشته باشند که این موضوع با دیود ممکن نیست.

**Comment by hamidtb** [comment]
سلام مجدد
امکان این که به جای 5 ولت ولتاژ 4.2 ولت از رگولاتور خروجی گرفته بشه و هم برای ماژول gsm و هم برای سایر قطعاتی که به 5 ولت نیاز دارن استفاده بشه وجود داره؟

**Comment by aKaReZa75** [comment]
> سلام مجدد امکان این که به جای 5 ولت ولتاژ 4.2 ولت از رگولاتور خروجی گرفته بشه و هم برای ماژول gsm و هم برای سایر قطعاتی که به 5 ولت نیاز دارن استفاده بشه وجود داره؟
> 
سلام و عرض ادب، این موضوع توی https://github.com/aKaReZa75/RCS_AVR/issues/2#issuecomment-2239743138 این قسمت بحث شده در موردش، اما به صورت خلاصه بپم، بله میشه ولی یک اگر و اما داره.
