### ISSUE TITLE
استفاده از رگولاتور های جدید

### ISSUE THREAD

**Issue by hamidtb** [aKaReZa75/RCS_AVR#8]
سلام، روزتون بخیر
نظرتون درباره استفاده از رگولاتور های جدید تر به جای AMS1117 چی هست
با توجه به این که با سوختن این رگولاتور، ورودی به خروجی متصل میشه و برای مدار بعد از رگولاتور خطرناک هست

رگولاتور هایی نظیر [TLV74333PDBVR](https://lionelectronic.ir/products/2492-TLV74333PDBVR)
[AP2125K-3.3TRG1](https://lionelectronic.ir/products/2713-AP2125K-3.3TRG1)
[ME6210A33PG](https://lionelectronic.ir/products/2834-ME6210A33PG)

**Comment by aKaReZa75** [comment]
سلام و عرض ادب، بله چرا که نه، استقبال هم میکنیم.
شما میتونید پروژه رو Fork بگیرید، تغییرات مد نظرتون رو اعمال کنید و به صورت Pull request برای بنده ارسال کنید تا توی پارت بعدی ویدئو بررسی کنیم.
