### ISSUE TITLE
استفاده از TI Webench Power Designer - Texas Instruments

### ISSUE THREAD

**Issue by hamidtb** [aKaReZa75/RCS_AVR#9]
سلام، روزتون بخیر
پیشنهاد میکنم جهت انتخاب و طراحی مدار رگولاتور از [TI Webench Power Designer - Texas Instruments](https://webench.ti.com/power-designer/) استفاده کنید
ممنونم

**Comment by aKaReZa75** [comment]
سلام و عرض ادب، ممنونم از شما، توی ویدئو این لینکی که شما زحمت کشیدین رو معرفی میکنم.
موفق باشید.
